language: node_js
node_js:
  - 10
stages:
  - buildAutomation
  - continousIntegration
before_install:
  - chmod +x gradlew
  - sudo apt-get update
addons:
  sonarcloud:
    organization: $SONAR_USER
    token: $SONAR_TOKEN
jobs:
  include:
    - stage: buildAutomation
      script:
        - ./gradlew sonarqube
        - ./gradlew test --test ch.noser.uek223.domain.user.unitTest.*
    - stage: continousIntegration
      script:
        - gradle test --tests ch.noser.uek223.domain.user.integTest.*
